# Generated by Django 2.2.4 on 2019-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=20)),
                ('payment', models.PositiveIntegerField()),
            ],
        ),
    ]
